### ISSUE TITLE
백엔드 1차 API 구현 역할분담

### ISSUE THREAD

**Issue by jangdayeon** [hanaro4-dIA/dia_be#1]
#### PB 프로필 컴포넌트
- [x] #15
- [x] #64
- [x] #163

#### 들어온 상담 요청 컴포넌트
- [x] #51
- [x] #57

#### 전체 상담 일정 캘린더 컴포넌트
- [x] #62
- [x] #63

#### 예정된 상담 일정 컴포넌트
- [x] #52

#### 손님 목록 컴포넌트
- [x] #32
- [x] #33

### PB 로그인 페이지
- [x] #113

#### 손님 정보 컴포넌트
- [x] #35

#### 상담 일지 리스트 컴포넌트
- [x] #20 

### stt 컴포넌트
- [x] #37
- [x] #91
- [x] #111

### 상담일지 작성하기 컴포넌트
- [x] #54
- [x] #55
- [x] #95
- [x] #100

### 쪽지 페이지
- [x] #42
- [x] #43
- [x] #44
- [x] #45

### 딕셔너리(keyword) 페이지
- [x] #109

#### 손님 목록 컴포넌트
- [x] #34
 
### VIP 메인 페이지
- [x] #89
- [x] #72
- [x] #78
- [x] #107

### VIP 상담 예약 페이지
- [x] #30
- [x] #38

### VIP 상담 확인 페이지
- [x] #86
- [x] #87

### VIP 상담 내역 페이지
- [x] #49
- [x] #74

### VIP 상담 상세 페이지
- [x] #75
- [x] #76
- [x] #77

### VIP 로그인 페이지
- [x] #141
- [x] #131

### VIP 회원가입 페이지
- [x] #132

### 알림 모달
- [x] #66
- [x] #69
- [x] #70

### 네비게이션
- [x] #208

**Comment by KyoungEun-creator** [comment]
dictionary 페이지를 위한 키워드 관련 api가 없는 것 같습니다....!

**Comment by jangdayeon** [comment]
모두들 정말 수고 많으셨습니다🥹👍👍
