### ISSUE TITLE
Fix - ResponseJournalDTO 필드 수정

### ISSUE THREAD

**Issue by daneng4** [hanaro4-dIA/dia_be#166]
## 📝설명

ResponseJournalDTO 필드 수정으로, 더 많은 데이터를 가져올 수 있게 변경

## ✅ TO-DO

- [ ] 해야 할 일 1
- [ ] 해야 할 일 2

## 🚀기타

기타 사항을 작성해 주세요

**Comment by KyoungEun-creator** [comment]
빠르게 처리해주셔서 다시한번 감사드립니다!!!!
